import type { Locale } from "./i18n";

// Ana sayfa bölüm başlıkları — "Popular experiences", "Explore destinations",
// "Every guide is verified", "Available now" vb. — 21 dil.
export type HomeSections = {
  everyGuideVerified: string;
  handpicked: string;
  popularExperiences: string;
  popularExpSub: string;
  exploreDestinations: string;
  exploreDestSub: string;
  availableNow: string;
};

export const homeSections: Record<Locale, HomeSections> = {
  en: { everyGuideVerified: "Every guide is verified", handpicked: "Handpicked", popularExperiences: "Popular experiences", popularExpSub: "Top-rated tours led by verified local guides across Turkey.", exploreDestinations: "Explore destinations", exploreDestSub: "Pick a city and meet the locals who know it best.", availableNow: "Available now" },
  tr: { everyGuideVerified: "Her rehber doğrulanmıştır", handpicked: "Özenle seçildi", popularExperiences: "Popüler deneyimler", popularExpSub: "Türkiye genelinde doğrulanmış yerel rehberlerin yönettiği en beğenilen turlar.", exploreDestinations: "Destinasyonları keşfet", exploreDestSub: "Bir şehir seç, orayı en iyi bilen yerellerle tanış.", availableNow: "Şimdi müsait" },
  de: { everyGuideVerified: "Jeder Guide ist geprüft", handpicked: "Handverlesen", popularExperiences: "Beliebte Erlebnisse", popularExpSub: "Top bewertete Touren von geprüften lokalen Guides in der ganzen Türkei.", exploreDestinations: "Reiseziele entdecken", exploreDestSub: "Wähle eine Stadt und triff die Locals, die sie am besten kennen.", availableNow: "Jetzt verfügbar" },
  fr: { everyGuideVerified: "Chaque guide est vérifié", handpicked: "Sélection", popularExperiences: "Expériences populaires", popularExpSub: "Visites les mieux notées menées par des guides locaux vérifiés à travers la Turquie.", exploreDestinations: "Explorer les destinations", exploreDestSub: "Choisis une ville et rencontre les locaux qui la connaissent le mieux.", availableNow: "Disponible maintenant" },
  hr: { everyGuideVerified: "Svaki vodič je provjeren", handpicked: "Ručno odabrano", popularExperiences: "Popularni doživljaji", popularExpSub: "Najbolje ocijenjene ture koje vode provjereni lokalni vodiči diljem Turske.", exploreDestinations: "Istraži odredišta", exploreDestSub: "Odaberi grad i upoznaj mještane koji ga najbolje poznaju.", availableNow: "Dostupno sada" },
  ro: { everyGuideVerified: "Fiecare ghid este verificat", handpicked: "Selectate manual", popularExperiences: "Experiențe populare", popularExpSub: "Tururi de top conduse de ghizi locali verificați din toată Turcia.", exploreDestinations: "Explorează destinațiile", exploreDestSub: "Alege un oraș și cunoaște localnicii care îl știu cel mai bine.", availableNow: "Disponibil acum" },
  zh: { everyGuideVerified: "每位向导都经过认证", handpicked: "精选", popularExperiences: "热门体验", popularExpSub: "由认证当地向导带领的高评分行程，遍布土耳其。", exploreDestinations: "探索目的地", exploreDestSub: "选择一座城市，结识最懂它的当地人。", availableNow: "现在可用" },
  ru: { everyGuideVerified: "Каждый гид проверен", handpicked: "Тщательный отбор", popularExperiences: "Популярные впечатления", popularExpSub: "Туры с высоким рейтингом от проверенных местных гидов по всей Турции.", exploreDestinations: "Откройте направления", exploreDestSub: "Выбери город и познакомься с местными, которые знают его лучше всех.", availableNow: "Доступно сейчас" },
  es: { everyGuideVerified: "Cada guía está verificado", handpicked: "Seleccionados", popularExperiences: "Experiencias populares", popularExpSub: "Tours mejor valorados con guías locales verificados por toda Turquía.", exploreDestinations: "Explora destinos", exploreDestSub: "Elige una ciudad y conoce a los locales que mejor la conocen.", availableNow: "Disponible ahora" },
  ko: { everyGuideVerified: "모든 가이드는 인증되었습니다", handpicked: "엄선", popularExperiences: "인기 체험", popularExpSub: "튀르키예 전역의 인증된 현지 가이드가 진행하는 최고 평점 투어.", exploreDestinations: "여행지 둘러보기", exploreDestSub: "도시를 고르고 그곳을 가장 잘 아는 현지인을 만나보세요.", availableNow: "지금 가능" },
  el: { everyGuideVerified: "Κάθε ξεναγός είναι πιστοποιημένος", handpicked: "Επιλεγμένα", popularExperiences: "Δημοφιλείς εμπειρίες", popularExpSub: "Κορυφαίες ξεναγήσεις από πιστοποιημένους ντόπιους ξεναγούς σε όλη την Τουρκία.", exploreDestinations: "Εξερεύνησε προορισμούς", exploreDestSub: "Διάλεξε μια πόλη και γνώρισε τους ντόπιους που την ξέρουν καλύτερα.", availableNow: "Διαθέσιμο τώρα" },
  ja: { everyGuideVerified: "すべてのガイドは認証済み", handpicked: "厳選", popularExperiences: "人気の体験", popularExpSub: "トルコ各地の認証済み地元ガイドによる高評価ツアー。", exploreDestinations: "目的地を探す", exploreDestSub: "都市を選んで、そこを最もよく知る地元の人に出会おう。", availableNow: "今すぐ利用可能" },
  bg: { everyGuideVerified: "Всеки водач е проверен", handpicked: "Подбрани", popularExperiences: "Популярни преживявания", popularExpSub: "Високо оценени турове с проверени местни водачи в цяла Турция.", exploreDestinations: "Открий дестинации", exploreDestSub: "Избери град и се запознай с местните, които го познават най-добре.", availableNow: "Налично сега" },
  sr: { everyGuideVerified: "Svaki vodič je proveren", handpicked: "Ručno odabrano", popularExperiences: "Popularni doživljaji", popularExpSub: "Najbolje ocenjene ture koje vode provereni lokalni vodiči širom Turske.", exploreDestinations: "Istraži destinacije", exploreDestSub: "Odaberi grad i upoznaj meštane koji ga najbolje poznaju.", availableNow: "Dostupno sada" },
  it: { everyGuideVerified: "Ogni guida è verificata", handpicked: "Selezionati", popularExperiences: "Esperienze popolari", popularExpSub: "Tour più votati con guide locali verificate in tutta la Turchia.", exploreDestinations: "Esplora le destinazioni", exploreDestSub: "Scegli una città e incontra i local che la conoscono meglio.", availableNow: "Disponibile ora" },
  ar: { everyGuideVerified: "كل مرشد موثّق", handpicked: "مختارة بعناية", popularExperiences: "تجارب شائعة", popularExpSub: "جولات بأعلى التقييمات يقودها مرشدون محليون موثّقون في جميع أنحاء تركيا.", exploreDestinations: "استكشف الوجهات", exploreDestSub: "اختر مدينة وتعرّف على السكان الذين يعرفونها أكثر.", availableNow: "متاح الآن" },
  nl: { everyGuideVerified: "Elke gids is geverifieerd", handpicked: "Met zorg gekozen", popularExperiences: "Populaire ervaringen", popularExpSub: "Best beoordeelde tours met geverifieerde lokale gidsen door heel Turkije.", exploreDestinations: "Ontdek bestemmingen", exploreDestSub: "Kies een stad en ontmoet de locals die haar het best kennen.", availableNow: "Nu beschikbaar" },
  pl: { everyGuideVerified: "Każdy przewodnik jest zweryfikowany", handpicked: "Wyselekcjonowane", popularExperiences: "Popularne doświadczenia", popularExpSub: "Najwyżej oceniane wycieczki z zweryfikowanymi lokalnymi przewodnikami w całej Turcji.", exploreDestinations: "Odkrywaj kierunki", exploreDestSub: "Wybierz miasto i poznaj mieszkańców, którzy znają je najlepiej.", availableNow: "Dostępne teraz" },
  uk: { everyGuideVerified: "Кожен гід перевірений", handpicked: "Ретельний відбір", popularExperiences: "Популярні враження", popularExpSub: "Тури з найвищим рейтингом від перевірених місцевих гідів по всій Туреччині.", exploreDestinations: "Досліджуй напрямки", exploreDestSub: "Обери місто й познайомся з місцевими, які знають його найкраще.", availableNow: "Доступно зараз" },
  id: { everyGuideVerified: "Setiap pemandu terverifikasi", handpicked: "Pilihan terbaik", popularExperiences: "Pengalaman populer", popularExpSub: "Tur dengan rating tertinggi dipandu pemandu lokal terverifikasi di seluruh Turki.", exploreDestinations: "Jelajahi destinasi", exploreDestSub: "Pilih kota dan temui warga lokal yang paling mengenalnya.", availableNow: "Tersedia sekarang" },
  pt: { everyGuideVerified: "Cada guia é verificado", handpicked: "Selecionados", popularExperiences: "Experiências populares", popularExpSub: "Tours mais bem avaliados com guias locais verificados por toda a Turquia.", exploreDestinations: "Explora destinos", exploreDestSub: "Escolhe uma cidade e conhece os locais que a conhecem melhor.", availableNow: "Disponível agora" },
};
