import type { Locale } from "./i18n";

// Navbar metinleri — 21 dil. Navbar.tsx'teki hardcoded İngilizce metinlerin yerine.
export type NavbarStrings = {
  tours: string;
  guides: string;
  becomeGuide: string;
  howItWorks: string;
  destinations: string;
  // SEO iç-link nav öğeleri — opsiyonel (eksik dilde İngilizce fallback).
  attractions?: string;
  blog?: string;
  startExploring: string;
  signIn: string;
  signUp: string;
  signOut: string;
  myProfile: string;
  browseTours: string;
  seeAllTours: string;
  getApp: string;
  browseByInterest: string;
  catHistory: string;
  catFood: string;
  catNature: string;
  catCulture: string;
  catAdventure: string;
  catArt: string;
};

export const navbarI18n: Record<Locale, NavbarStrings> = {
  en: { tours: "Tours", guides: "Guides", becomeGuide: "Become a guide", howItWorks: "How it works", destinations: "Destinations", startExploring: "Start exploring", signIn: "Sign in", signUp: "Register", signOut: "Sign out", myProfile: "My profile", browseTours: "Browse tours", seeAllTours: "See all tours", getApp: "Get the app", browseByInterest: "Browse by interest", catHistory: "History", catFood: "Food & Drink", catNature: "Nature", catCulture: "Culture", catAdventure: "Adventure", catArt: "Art", attractions: "Attractions", blog: "Blog" },
  tr: { tours: "Turlar", guides: "Rehberler", becomeGuide: "Rehber ol", howItWorks: "Nasıl çalışır", destinations: "Yerler", startExploring: "Keşfetmeye başla", signIn: "Giriş yap", signUp: "Kayıt ol", signOut: "Çıkış yap", myProfile: "Profilim", browseTours: "Turlara göz at", seeAllTours: "Tüm turları gör", getApp: "Uygulamayı indir", browseByInterest: "İlgi alanına göre", catHistory: "Tarih", catFood: "Yeme & İçme", catNature: "Doğa", catCulture: "Kültür", catAdventure: "Macera", catArt: "Sanat", attractions: "Gezilecek Yerler", blog: "Blog" },
  de: { tours: "Touren", guides: "Guides", becomeGuide: "Guide werden", howItWorks: "So funktioniert's", destinations: "Reiseziele", attractions: "Sehenswürdigkeiten", blog: "Blog", startExploring: "Jetzt entdecken", signIn: "Anmelden", signUp: "Registrieren", signOut: "Abmelden", myProfile: "Mein Profil", browseTours: "Touren ansehen", seeAllTours: "Alle Touren ansehen", getApp: "App holen", browseByInterest: "Nach Interesse", catHistory: "Geschichte", catFood: "Essen & Trinken", catNature: "Natur", catCulture: "Kultur", catAdventure: "Abenteuer", catArt: "Kunst" },
  fr: { tours: "Visites", guides: "Guides", becomeGuide: "Devenir guide", howItWorks: "Comment ça marche", destinations: "Destinations", attractions: "Sites à visiter", blog: "Blog", startExploring: "Explorer", signIn: "Se connecter", signUp: "S'inscrire", signOut: "Se déconnecter", myProfile: "Mon profil", browseTours: "Voir les visites", seeAllTours: "Voir toutes les visites", getApp: "Obtenir l’app", browseByInterest: "Par centre d'intérêt", catHistory: "Histoire", catFood: "Gastronomie", catNature: "Nature", catCulture: "Culture", catAdventure: "Aventure", catArt: "Art" },
  hr: { tours: "Ture", guides: "Vodiči", becomeGuide: "Postani vodič", howItWorks: "Kako funkcionira", destinations: "Odredišta", attractions: "Znamenitosti", blog: "Blog", startExploring: "Istraži", signIn: "Prijava", signUp: "Registracija", signOut: "Odjava", myProfile: "Moj profil", browseTours: "Pregledaj ture", seeAllTours: "Prikaži sve ture", getApp: "Preuzmi aplikaciju", browseByInterest: "Po interesu", catHistory: "Povijest", catFood: "Hrana i piće", catNature: "Priroda", catCulture: "Kultura", catAdventure: "Avantura", catArt: "Umjetnost" },
  ro: { tours: "Tururi", guides: "Ghizi", becomeGuide: "Devino ghid", howItWorks: "Cum funcționează", destinations: "Destinații", attractions: "Obiective turistice", blog: "Blog", startExploring: "Explorează", signIn: "Autentificare", signUp: "Înregistrare", signOut: "Deconectare", myProfile: "Profilul meu", browseTours: "Vezi tururile", seeAllTours: "Vezi toate tururile", getApp: "Descarcă aplicația", browseByInterest: "După interes", catHistory: "Istorie", catFood: "Mâncare & Băutură", catNature: "Natură", catCulture: "Cultură", catAdventure: "Aventură", catArt: "Artă" },
  zh: { tours: "行程", guides: "向导", becomeGuide: "成为向导", howItWorks: "使用方法", destinations: "目的地", attractions: "热门景点", blog: "博客", startExploring: "开始探索", signIn: "登录", signUp: "注册", signOut: "退出", myProfile: "我的资料", browseTours: "浏览行程", seeAllTours: "查看所有行程", getApp: "获取应用", browseByInterest: "按兴趣浏览", catHistory: "历史", catFood: "美食", catNature: "自然", catCulture: "文化", catAdventure: "探险", catArt: "艺术" },
  ru: { tours: "Туры", guides: "Гиды", becomeGuide: "Стать гидом", howItWorks: "Как это работает", destinations: "Направления", attractions: "Достопримечательности", blog: "Блог", startExploring: "Начать", signIn: "Войти", signUp: "Регистрация", signOut: "Выйти", myProfile: "Мой профиль", browseTours: "Смотреть туры", seeAllTours: "Все туры", getApp: "Скачать приложение", browseByInterest: "По интересам", catHistory: "История", catFood: "Еда и напитки", catNature: "Природа", catCulture: "Культура", catAdventure: "Приключения", catArt: "Искусство" },
  es: { tours: "Tours", guides: "Guías", becomeGuide: "Conviértete en guía", howItWorks: "Cómo funciona", destinations: "Destinos", attractions: "Lugares de interés", blog: "Blog", startExploring: "Explorar", signIn: "Iniciar sesión", signUp: "Registrarse", signOut: "Cerrar sesión", myProfile: "Mi perfil", browseTours: "Ver tours", seeAllTours: "Ver todos los tours", getApp: "Descargar la app", browseByInterest: "Por interés", catHistory: "Historia", catFood: "Gastronomía", catNature: "Naturaleza", catCulture: "Cultura", catAdventure: "Aventura", catArt: "Arte" },
  ko: { tours: "투어", guides: "가이드", becomeGuide: "가이드 되기", howItWorks: "이용 방법", destinations: "여행지", attractions: "주요 명소", blog: "블로그", startExploring: "탐색 시작", signIn: "로그인", signUp: "회원가입", signOut: "로그아웃", myProfile: "내 프로필", browseTours: "투어 둘러보기", seeAllTours: "모든 투어 보기", getApp: "앱 다운로드", browseByInterest: "관심사별", catHistory: "역사", catFood: "음식", catNature: "자연", catCulture: "문화", catAdventure: "모험", catArt: "예술" },
  el: { tours: "Ξεναγήσεις", guides: "Ξεναγοί", becomeGuide: "Γίνε ξεναγός", howItWorks: "Πώς λειτουργεί", destinations: "Προορισμοί", attractions: "Αξιοθέατα", blog: "Ιστολόγιο", startExploring: "Ξεκίνα", signIn: "Σύνδεση", signUp: "Εγγραφή", signOut: "Αποσύνδεση", myProfile: "Το προφίλ μου", browseTours: "Δες ξεναγήσεις", seeAllTours: "Όλες οι ξεναγήσεις", getApp: "Λήψη εφαρμογής", browseByInterest: "Ανά ενδιαφέρον", catHistory: "Ιστορία", catFood: "Φαγητό & Ποτό", catNature: "Φύση", catCulture: "Πολιτισμός", catAdventure: "Περιπέτεια", catArt: "Τέχνη" },
  ja: { tours: "ツアー", guides: "ガイド", becomeGuide: "ガイドになる", howItWorks: "使い方", destinations: "目的地", attractions: "観光スポット", blog: "ブログ", startExploring: "始める", signIn: "ログイン", signUp: "登録", signOut: "ログアウト", myProfile: "マイプロフィール", browseTours: "ツアーを見る", seeAllTours: "すべてのツアー", getApp: "アプリを入手", browseByInterest: "興味から探す", catHistory: "歴史", catFood: "グルメ", catNature: "自然", catCulture: "文化", catAdventure: "アドベンチャー", catArt: "アート" },
  bg: { tours: "Турове", guides: "Водачи", becomeGuide: "Стани водач", howItWorks: "Как работи", destinations: "Дестинации", attractions: "Забележителности", blog: "Блог", startExploring: "Започни", signIn: "Вход", signUp: "Регистрация", signOut: "Изход", myProfile: "Моят профил", browseTours: "Разгледай турове", seeAllTours: "Всички турове", getApp: "Изтегли приложението", browseByInterest: "По интерес", catHistory: "История", catFood: "Храна и напитки", catNature: "Природа", catCulture: "Култура", catAdventure: "Приключение", catArt: "Изкуство" },
  sr: { tours: "Ture", guides: "Vodiči", becomeGuide: "Postani vodič", howItWorks: "Kako funkcioniše", destinations: "Destinacije", attractions: "Znamenitosti", blog: "Blog", startExploring: "Istraži", signIn: "Prijava", signUp: "Registracija", signOut: "Odjava", myProfile: "Moj profil", browseTours: "Pregledaj ture", seeAllTours: "Prikaži sve ture", getApp: "Preuzmi aplikaciju", browseByInterest: "Po interesovanju", catHistory: "Istorija", catFood: "Hrana i piće", catNature: "Priroda", catCulture: "Kultura", catAdventure: "Avantura", catArt: "Umetnost" },
  it: { tours: "Tour", guides: "Guide", becomeGuide: "Diventa guida", howItWorks: "Come funziona", destinations: "Destinazioni", attractions: "Attrazioni", blog: "Blog", startExploring: "Inizia", signIn: "Accedi", signUp: "Registrati", signOut: "Esci", myProfile: "Il mio profilo", browseTours: "Sfoglia i tour", seeAllTours: "Vedi tutti i tour", getApp: "Scarica l’app", browseByInterest: "Per interesse", catHistory: "Storia", catFood: "Cibo & Bevande", catNature: "Natura", catCulture: "Cultura", catAdventure: "Avventura", catArt: "Arte" },
  ar: { tours: "الجولات", guides: "المرشدون", becomeGuide: "كن مرشدًا", howItWorks: "كيف يعمل", destinations: "الوجهات", attractions: "المعالم السياحية", blog: "المدونة", startExploring: "ابدأ الاستكشاف", signIn: "تسجيل الدخول", signUp: "إنشاء حساب", signOut: "تسجيل الخروج", myProfile: "ملفي", browseTours: "تصفح الجولات", seeAllTours: "كل الجولات", getApp: "حمّل التطبيق", browseByInterest: "حسب الاهتمام", catHistory: "تاريخ", catFood: "طعام وشراب", catNature: "طبيعة", catCulture: "ثقافة", catAdventure: "مغامرة", catArt: "فن" },
  nl: { tours: "Tours", guides: "Gidsen", becomeGuide: "Word gids", howItWorks: "Hoe het werkt", destinations: "Bestemmingen", attractions: "Bezienswaardigheden", blog: "Blog", startExploring: "Ontdekken", signIn: "Inloggen", signUp: "Registreren", signOut: "Uitloggen", myProfile: "Mijn profiel", browseTours: "Bekijk tours", seeAllTours: "Alle tours bekijken", getApp: "App downloaden", browseByInterest: "Op interesse", catHistory: "Geschiedenis", catFood: "Eten & Drinken", catNature: "Natuur", catCulture: "Cultuur", catAdventure: "Avontuur", catArt: "Kunst" },
  pl: { tours: "Wycieczki", guides: "Przewodnicy", becomeGuide: "Zostań przewodnikiem", howItWorks: "Jak to działa", destinations: "Kierunki", attractions: "Atrakcje", blog: "Blog", startExploring: "Zacznij", signIn: "Zaloguj się", signUp: "Zarejestruj się", signOut: "Wyloguj się", myProfile: "Mój profil", browseTours: "Przeglądaj wycieczki", seeAllTours: "Zobacz wszystkie", getApp: "Pobierz aplikację", browseByInterest: "Według zainteresowań", catHistory: "Historia", catFood: "Jedzenie i napoje", catNature: "Natura", catCulture: "Kultura", catAdventure: "Przygoda", catArt: "Sztuka" },
  uk: { tours: "Тури", guides: "Гіди", becomeGuide: "Стати гідом", howItWorks: "Як це працює", destinations: "Напрямки", attractions: "Визначні місця", blog: "Блог", startExploring: "Почати", signIn: "Увійти", signUp: "Реєстрація", signOut: "Вийти", myProfile: "Мій профіль", browseTours: "Переглянути тури", seeAllTours: "Усі тури", getApp: "Завантажити застосунок", browseByInterest: "За інтересами", catHistory: "Історія", catFood: "Їжа та напої", catNature: "Природа", catCulture: "Культура", catAdventure: "Пригоди", catArt: "Мистецтво" },
  id: { tours: "Tur", guides: "Pemandu", becomeGuide: "Jadi pemandu", howItWorks: "Cara kerja", destinations: "Destinasi", attractions: "Tempat Wisata", blog: "Blog", startExploring: "Mulai jelajah", signIn: "Masuk", signUp: "Daftar", signOut: "Keluar", myProfile: "Profil saya", browseTours: "Jelajahi tur", seeAllTours: "Lihat semua tur", getApp: "Dapatkan aplikasi", browseByInterest: "Berdasarkan minat", catHistory: "Sejarah", catFood: "Makanan & Minuman", catNature: "Alam", catCulture: "Budaya", catAdventure: "Petualangan", catArt: "Seni" },
  pt: { tours: "Tours", guides: "Guias", becomeGuide: "Seja um guia", howItWorks: "Como funciona", destinations: "Destinos", attractions: "Atrações", blog: "Blog", startExploring: "Explorar", signIn: "Entrar", signUp: "Registar", signOut: "Sair", myProfile: "O meu perfil", browseTours: "Ver tours", seeAllTours: "Ver todos os tours", getApp: "Obter a app", browseByInterest: "Por interesse", catHistory: "História", catFood: "Comida & Bebida", catNature: "Natureza", catCulture: "Cultura", catAdventure: "Aventura", catArt: "Arte" },
};
