import type { Locale } from "./i18n";

// Ana sayfadaki kalan hardcoded metinler — arama barı, kategori başlığı, trust bar,
// footer legal/çalışma saatleri vb. — 21 dil. Kategori etiketleri için navbar-i18n.
export type UiExtra = {
  searchSubtitle: string;
  searchWhereTo: string;
  searchTryFood: string;
  searchTryPrefix: string; // "Try {city}…" → `${searchTryPrefix} ${city}…`
  explore: string;
  popular: string;
  whatAreYouInto: string;
  realLocals: string;
  legal: string;
  securityPayment: string;
  terms: string;
  privacy: string;
  cancellation: string;
  distanceSales: string;
  preInfo: string;
  kvkk: string;
  cookies: string;
  workingHours: string;
  trustLine: string;
  trustRatingTitle: string;
  trustRatingSub: string;
  trustVerifiedTitle: string;
  trustVerifiedSub: string;
  trustCancelTitle: string;
  trustCancelSub: string;
  trustInstantTitle: string;
  trustInstantSub: string;
};

export const uiExtra: Record<Locale, UiExtra> = {
  en: { searchSubtitle: "Discover guides & tours near you", searchWhereTo: "Where to?", searchTryFood: "Try a food tour…", searchTryPrefix: "Try", explore: "Explore", popular: "Popular", whatAreYouInto: "What are you into?", realLocals: "Real locals. Real stories. Real discovery.", legal: "Legal", securityPayment: "Security & Payment", terms: "Terms of Service", privacy: "Privacy Policy", cancellation: "Cancellation & Refunds", distanceSales: "Distance Sales Agreement", preInfo: "Pre-Information Form", kvkk: "Data Protection Notice", cookies: "Cookie Policy", workingHours: "Working hours: Weekdays 09:00 – 18:00 (UTC+3)", trustLine: "SSL Secured · Licensed Guides · Secure Booking", trustRatingTitle: "4.9 average rating", trustRatingSub: "From real travellers", trustVerifiedTitle: "100% verified guides", trustVerifiedSub: "ID & licence checked", trustCancelTitle: "Free cancellation", trustCancelSub: "On most experiences", trustInstantTitle: "Instant booking", trustInstantSub: "Confirm in seconds" },
  tr: { searchSubtitle: "Yakınındaki rehber ve turları keşfet", searchWhereTo: "Nereye?", searchTryFood: "Yemek turu dene…", searchTryPrefix: "Dene:", explore: "Keşfet", popular: "Popüler", whatAreYouInto: "Neye ilgin var?", realLocals: "Gerçek yereller. Gerçek hikâyeler. Gerçek keşif.", legal: "Yasal", securityPayment: "Güvenlik & Ödeme", terms: "Kullanım Şartları", privacy: "Gizlilik Politikası", cancellation: "İptal & İade", distanceSales: "Mesafeli Satış Sözleşmesi", preInfo: "Ön Bilgilendirme Formu", kvkk: "KVKK Aydınlatma", cookies: "Çerez Politikası", workingHours: "Çalışma saatleri: Hafta içi 09:00 – 18:00 (UTC+3)", trustLine: "SSL Korumalı · Lisanslı Rehberler · Güvenli Rezervasyon", trustRatingTitle: "4.9 ortalama puan", trustRatingSub: "Gerçek gezginlerden", trustVerifiedTitle: "%100 doğrulanmış rehber", trustVerifiedSub: "Kimlik & lisans kontrollü", trustCancelTitle: "Ücretsiz iptal", trustCancelSub: "Çoğu deneyimde", trustInstantTitle: "Anında rezervasyon", trustInstantSub: "Saniyeler içinde onay" },
  de: { searchSubtitle: "Entdecke Guides & Touren in deiner Nähe", searchWhereTo: "Wohin?", searchTryFood: "Probier eine Food-Tour…", searchTryPrefix: "Probier", explore: "Entdecken", popular: "Beliebt", whatAreYouInto: "Worauf hast du Lust?", realLocals: "Echte Locals. Echte Geschichten. Echte Entdeckungen.", legal: "Rechtliches", securityPayment: "Sicherheit & Zahlung", terms: "Nutzungsbedingungen", privacy: "Datenschutz", cancellation: "Stornierung & Rückerstattung", distanceSales: "Fernabsatzvertrag", preInfo: "Vorab-Informationsformular", kvkk: "Datenschutzhinweis", cookies: "Cookie-Richtlinie", workingHours: "Öffnungszeiten: Wochentags 09:00 – 18:00 (UTC+3)", trustLine: "SSL-geschützt · Lizenzierte Guides · Sichere Buchung", trustRatingTitle: "4,9 Durchschnitt", trustRatingSub: "Von echten Reisenden", trustVerifiedTitle: "100% geprüfte Guides", trustVerifiedSub: "ID & Lizenz geprüft", trustCancelTitle: "Kostenlose Stornierung", trustCancelSub: "Bei den meisten Touren", trustInstantTitle: "Sofortbuchung", trustInstantSub: "In Sekunden bestätigt" },
  fr: { searchSubtitle: "Découvre guides & visites près de toi", searchWhereTo: "Où aller ?", searchTryFood: "Essaie une visite gourmande…", searchTryPrefix: "Essaie", explore: "Explorer", popular: "Populaire", whatAreYouInto: "Qu'est-ce qui te tente ?", realLocals: "De vrais locaux. De vraies histoires. De vraies découvertes.", legal: "Mentions légales", securityPayment: "Sécurité & Paiement", terms: "Conditions d'utilisation", privacy: "Politique de confidentialité", cancellation: "Annulation & Remboursement", distanceSales: "Contrat de vente à distance", preInfo: "Formulaire de pré-information", kvkk: "Avis de protection des données", cookies: "Politique de cookies", workingHours: "Heures d'ouverture : En semaine 09:00 – 18:00 (UTC+3)", trustLine: "SSL sécurisé · Guides agréés · Réservation sécurisée", trustRatingTitle: "4,9 de moyenne", trustRatingSub: "De vrais voyageurs", trustVerifiedTitle: "Guides 100% vérifiés", trustVerifiedSub: "Pièce d'identité & licence vérifiées", trustCancelTitle: "Annulation gratuite", trustCancelSub: "Sur la plupart des visites", trustInstantTitle: "Réservation instantanée", trustInstantSub: "Confirmé en secondes" },
  hr: { searchSubtitle: "Otkrij vodiče i ture u blizini", searchWhereTo: "Kamo?", searchTryFood: "Probaj gastro turu…", searchTryPrefix: "Probaj", explore: "Istraži", popular: "Popularno", whatAreYouInto: "Što te zanima?", realLocals: "Pravi mještani. Prave priče. Pravo otkriće.", legal: "Pravno", securityPayment: "Sigurnost i plaćanje", terms: "Uvjeti korištenja", privacy: "Pravila privatnosti", cancellation: "Otkazivanje i povrat", distanceSales: "Ugovor o prodaji na daljinu", preInfo: "Obrazac prethodne obavijesti", kvkk: "Obavijest o zaštiti podataka", cookies: "Pravila o kolačićima", workingHours: "Radno vrijeme: Radnim danom 09:00 – 18:00 (UTC+3)", trustLine: "SSL zaštita · Licencirani vodiči · Sigurna rezervacija", trustRatingTitle: "Prosječna ocjena 4.9", trustRatingSub: "Od pravih putnika", trustVerifiedTitle: "100% provjereni vodiči", trustVerifiedSub: "Provjerena osobna i licenca", trustCancelTitle: "Besplatno otkazivanje", trustCancelSub: "Za većinu doživljaja", trustInstantTitle: "Trenutna rezervacija", trustInstantSub: "Potvrda u sekundama" },
  ro: { searchSubtitle: "Descoperă ghizi și tururi din apropiere", searchWhereTo: "Încotro?", searchTryFood: "Încearcă un tur culinar…", searchTryPrefix: "Încearcă", explore: "Explorează", popular: "Populare", whatAreYouInto: "Ce te pasionează?", realLocals: "Localnici reali. Povești reale. Descoperire reală.", legal: "Legal", securityPayment: "Securitate & Plată", terms: "Termeni și condiții", privacy: "Politica de confidențialitate", cancellation: "Anulare & Rambursare", distanceSales: "Contract de vânzare la distanță", preInfo: "Formular de pre-informare", kvkk: "Notă privind protecția datelor", cookies: "Politica de cookie-uri", workingHours: "Program: În timpul săptămânii 09:00 – 18:00 (UTC+3)", trustLine: "Protejat SSL · Ghizi licențiați · Rezervare sigură", trustRatingTitle: "Rating mediu 4.9", trustRatingSub: "De la călători reali", trustVerifiedTitle: "Ghizi 100% verificați", trustVerifiedSub: "Act & licență verificate", trustCancelTitle: "Anulare gratuită", trustCancelSub: "La majoritatea experiențelor", trustInstantTitle: "Rezervare instantanee", trustInstantSub: "Confirmare în secunde" },
  zh: { searchSubtitle: "发现你附近的向导和行程", searchWhereTo: "去哪里？", searchTryFood: "试试美食之旅…", searchTryPrefix: "试试", explore: "探索", popular: "热门", whatAreYouInto: "你喜欢什么？", realLocals: "真实的当地人。真实的故事。真实的发现。", legal: "法律", securityPayment: "安全与支付", terms: "服务条款", privacy: "隐私政策", cancellation: "取消与退款", distanceSales: "远程销售协议", preInfo: "预先告知表", kvkk: "数据保护声明", cookies: "Cookie 政策", workingHours: "工作时间：工作日 09:00 – 18:00 (UTC+3)", trustLine: "SSL 加密 · 持证向导 · 安全预订", trustRatingTitle: "4.9 平均评分", trustRatingSub: "来自真实旅行者", trustVerifiedTitle: "100% 认证向导", trustVerifiedSub: "已核验身份与执照", trustCancelTitle: "免费取消", trustCancelSub: "适用于大多数体验", trustInstantTitle: "即时预订", trustInstantSub: "几秒内确认" },
  ru: { searchSubtitle: "Найди гидов и туры рядом", searchWhereTo: "Куда?", searchTryFood: "Попробуй гастротур…", searchTryPrefix: "Попробуй", explore: "Смотреть", popular: "Популярное", whatAreYouInto: "Что тебе интересно?", realLocals: "Настоящие местные. Настоящие истории. Настоящие открытия.", legal: "Правовая информация", securityPayment: "Безопасность и оплата", terms: "Условия использования", privacy: "Политика конфиденциальности", cancellation: "Отмена и возврат", distanceSales: "Договор дистанционной продажи", preInfo: "Форма предварительного уведомления", kvkk: "Уведомление о защите данных", cookies: "Политика cookie", workingHours: "Часы работы: По будням 09:00 – 18:00 (UTC+3)", trustLine: "SSL-защита · Лицензированные гиды · Безопасное бронирование", trustRatingTitle: "Рейтинг 4.9", trustRatingSub: "От настоящих путешественников", trustVerifiedTitle: "100% проверенные гиды", trustVerifiedSub: "Документы и лицензия проверены", trustCancelTitle: "Бесплатная отмена", trustCancelSub: "На большинстве туров", trustInstantTitle: "Мгновенное бронирование", trustInstantSub: "Подтверждение за секунды" },
  es: { searchSubtitle: "Descubre guías y tours cerca de ti", searchWhereTo: "¿A dónde?", searchTryFood: "Prueba un tour gastronómico…", searchTryPrefix: "Prueba", explore: "Explorar", popular: "Popular", whatAreYouInto: "¿Qué te gusta?", realLocals: "Locales de verdad. Historias de verdad. Descubrimiento de verdad.", legal: "Legal", securityPayment: "Seguridad y Pago", terms: "Términos de servicio", privacy: "Política de privacidad", cancellation: "Cancelación y Reembolsos", distanceSales: "Contrato de venta a distancia", preInfo: "Formulario de información previa", kvkk: "Aviso de protección de datos", cookies: "Política de cookies", workingHours: "Horario: Días laborables 09:00 – 18:00 (UTC+3)", trustLine: "Protegido con SSL · Guías con licencia · Reserva segura", trustRatingTitle: "4,9 de media", trustRatingSub: "De viajeros reales", trustVerifiedTitle: "Guías 100% verificados", trustVerifiedSub: "DNI y licencia comprobados", trustCancelTitle: "Cancelación gratis", trustCancelSub: "En la mayoría de experiencias", trustInstantTitle: "Reserva instantánea", trustInstantSub: "Confirma en segundos" },
  ko: { searchSubtitle: "주변의 가이드와 투어를 둘러보세요", searchWhereTo: "어디로?", searchTryFood: "푸드 투어 어때요…", searchTryPrefix: "추천:", explore: "탐색", popular: "인기", whatAreYouInto: "무엇에 관심 있나요?", realLocals: "진짜 현지인. 진짜 이야기. 진짜 발견.", legal: "법적 고지", securityPayment: "보안 & 결제", terms: "이용약관", privacy: "개인정보 처리방침", cancellation: "취소 & 환불", distanceSales: "통신판매 계약", preInfo: "사전 정보 양식", kvkk: "개인정보 보호 고지", cookies: "쿠키 정책", workingHours: "운영 시간: 평일 09:00 – 18:00 (UTC+3)", trustLine: "SSL 보안 · 공인 가이드 · 안전한 예약", trustRatingTitle: "평균 4.9점", trustRatingSub: "실제 여행자 평가", trustVerifiedTitle: "100% 인증 가이드", trustVerifiedSub: "신분증 & 자격 확인", trustCancelTitle: "무료 취소", trustCancelSub: "대부분의 체험에서", trustInstantTitle: "즉시 예약", trustInstantSub: "몇 초 만에 확정" },
  el: { searchSubtitle: "Ανακάλυψε ξεναγούς & ξεναγήσεις κοντά σου", searchWhereTo: "Πού πας;", searchTryFood: "Δοκίμασε γαστρονομική ξενάγηση…", searchTryPrefix: "Δοκίμασε", explore: "Εξερεύνηση", popular: "Δημοφιλή", whatAreYouInto: "Τι σου αρέσει;", realLocals: "Αληθινοί ντόπιοι. Αληθινές ιστορίες. Αληθινή ανακάλυψη.", legal: "Νομικά", securityPayment: "Ασφάλεια & Πληρωμή", terms: "Όροι χρήσης", privacy: "Πολιτική απορρήτου", cancellation: "Ακύρωση & Επιστροφές", distanceSales: "Σύμβαση εξ αποστάσεως πώλησης", preInfo: "Έντυπο προ-ενημέρωσης", kvkk: "Ειδοποίηση προστασίας δεδομένων", cookies: "Πολιτική cookies", workingHours: "Ώρες λειτουργίας: Καθημερινές 09:00 – 18:00 (UTC+3)", trustLine: "Προστασία SSL · Αδειούχοι ξεναγοί · Ασφαλής κράτηση", trustRatingTitle: "4.9 μέση βαθμολογία", trustRatingSub: "Από αληθινούς ταξιδιώτες", trustVerifiedTitle: "100% επαληθευμένοι ξεναγοί", trustVerifiedSub: "Ελεγμένη ταυτότητα & άδεια", trustCancelTitle: "Δωρεάν ακύρωση", trustCancelSub: "Στις περισσότερες εμπειρίες", trustInstantTitle: "Άμεση κράτηση", trustInstantSub: "Επιβεβαίωση σε δευτερόλεπτα" },
  ja: { searchSubtitle: "近くのガイドとツアーを見つけよう", searchWhereTo: "どこへ？", searchTryFood: "フードツアーはいかが…", searchTryPrefix: "おすすめ:", explore: "探す", popular: "人気", whatAreYouInto: "何に興味がある？", realLocals: "本物の地元の人。本物の物語。本物の発見。", legal: "法的情報", securityPayment: "セキュリティと支払い", terms: "利用規約", privacy: "プライバシーポリシー", cancellation: "キャンセルと返金", distanceSales: "通信販売契約", preInfo: "事前情報フォーム", kvkk: "データ保護に関する通知", cookies: "Cookie ポリシー", workingHours: "営業時間: 平日 09:00 – 18:00 (UTC+3)", trustLine: "SSL保護 · 公認ガイド · 安全な予約", trustRatingTitle: "平均4.9", trustRatingSub: "本物の旅行者から", trustVerifiedTitle: "100%認証済みガイド", trustVerifiedSub: "身分証・資格を確認", trustCancelTitle: "無料キャンセル", trustCancelSub: "ほとんどの体験で", trustInstantTitle: "即時予約", trustInstantSub: "数秒で確定" },
  bg: { searchSubtitle: "Открий водачи и турове наблизо", searchWhereTo: "Накъде?", searchTryFood: "Опитай кулинарен тур…", searchTryPrefix: "Опитай", explore: "Разгледай", popular: "Популярни", whatAreYouInto: "Какво те влече?", realLocals: "Истински местни. Истински истории. Истинско откритие.", legal: "Правна информация", securityPayment: "Сигурност и плащане", terms: "Условия за ползване", privacy: "Политика за поверителност", cancellation: "Анулиране и възстановяване", distanceSales: "Договор за продажба от разстояние", preInfo: "Формуляр за предварителна информация", kvkk: "Известие за защита на данните", cookies: "Политика за бисквитки", workingHours: "Работно време: Делнични дни 09:00 – 18:00 (UTC+3)", trustLine: "SSL защита · Лицензирани водачи · Сигурна резервация", trustRatingTitle: "Рейтинг 4.9", trustRatingSub: "От истински пътешественици", trustVerifiedTitle: "100% проверени водачи", trustVerifiedSub: "Проверени документ и лиценз", trustCancelTitle: "Безплатно анулиране", trustCancelSub: "За повечето преживявания", trustInstantTitle: "Незабавна резервация", trustInstantSub: "Потвърждение за секунди" },
  sr: { searchSubtitle: "Otkrij vodiče i ture u blizini", searchWhereTo: "Kuda?", searchTryFood: "Probaj gastro turu…", searchTryPrefix: "Probaj", explore: "Istraži", popular: "Popularno", whatAreYouInto: "Šta te zanima?", realLocals: "Pravi meštani. Prave priče. Pravo otkriće.", legal: "Pravno", securityPayment: "Bezbednost i plaćanje", terms: "Uslovi korišćenja", privacy: "Politika privatnosti", cancellation: "Otkazivanje i povraćaj", distanceSales: "Ugovor o prodaji na daljinu", preInfo: "Obrazac prethodnog obaveštenja", kvkk: "Obaveštenje o zaštiti podataka", cookies: "Politika kolačića", workingHours: "Radno vreme: Radnim danima 09:00 – 18:00 (UTC+3)", trustLine: "SSL zaštita · Licencirani vodiči · Bezbedna rezervacija", trustRatingTitle: "Prosečna ocena 4.9", trustRatingSub: "Od pravih putnika", trustVerifiedTitle: "100% provereni vodiči", trustVerifiedSub: "Provereni lična i licenca", trustCancelTitle: "Besplatno otkazivanje", trustCancelSub: "Za većinu doživljaja", trustInstantTitle: "Trenutna rezervacija", trustInstantSub: "Potvrda za sekunde" },
  it: { searchSubtitle: "Scopri guide e tour vicino a te", searchWhereTo: "Dove?", searchTryFood: "Prova un tour gastronomico…", searchTryPrefix: "Prova", explore: "Esplora", popular: "Popolari", whatAreYouInto: "Cosa ti piace?", realLocals: "Veri local. Vere storie. Vera scoperta.", legal: "Note legali", securityPayment: "Sicurezza e Pagamento", terms: "Termini di servizio", privacy: "Informativa sulla privacy", cancellation: "Cancellazione e Rimborsi", distanceSales: "Contratto di vendita a distanza", preInfo: "Modulo di pre-informazione", kvkk: "Informativa sulla protezione dei dati", cookies: "Politica sui cookie", workingHours: "Orari: Giorni feriali 09:00 – 18:00 (UTC+3)", trustLine: "Protetto da SSL · Guide autorizzate · Prenotazione sicura", trustRatingTitle: "4,9 di media", trustRatingSub: "Da veri viaggiatori", trustVerifiedTitle: "Guide verificate al 100%", trustVerifiedSub: "Documento e licenza verificati", trustCancelTitle: "Cancellazione gratuita", trustCancelSub: "Sulla maggior parte dei tour", trustInstantTitle: "Prenotazione immediata", trustInstantSub: "Conferma in secondi" },
  ar: { searchSubtitle: "اكتشف المرشدين والجولات القريبة منك", searchWhereTo: "إلى أين؟", searchTryFood: "جرّب جولة طعام…", searchTryPrefix: "جرّب", explore: "استكشف", popular: "الأكثر رواجًا", whatAreYouInto: "ما الذي يثير اهتمامك؟", realLocals: "سكان حقيقيون. قصص حقيقية. اكتشاف حقيقي.", legal: "قانوني", securityPayment: "الأمان والدفع", terms: "شروط الخدمة", privacy: "سياسة الخصوصية", cancellation: "الإلغاء والاسترداد", distanceSales: "عقد البيع عن بُعد", preInfo: "نموذج المعلومات المسبقة", kvkk: "إشعار حماية البيانات", cookies: "سياسة ملفات تعريف الارتباط", workingHours: "ساعات العمل: أيام الأسبوع 09:00 – 18:00 (UTC+3)", trustLine: "محمي بـ SSL · مرشدون مرخّصون · حجز آمن", trustRatingTitle: "متوسط التقييم 4.9", trustRatingSub: "من مسافرين حقيقيين", trustVerifiedTitle: "مرشدون موثّقون 100%", trustVerifiedSub: "تم التحقق من الهوية والرخصة", trustCancelTitle: "إلغاء مجاني", trustCancelSub: "في معظم التجارب", trustInstantTitle: "حجز فوري", trustInstantSub: "تأكيد خلال ثوانٍ" },
  nl: { searchSubtitle: "Ontdek gidsen & tours bij jou in de buurt", searchWhereTo: "Waarheen?", searchTryFood: "Probeer een foodtour…", searchTryPrefix: "Probeer", explore: "Ontdekken", popular: "Populair", whatAreYouInto: "Waar hou je van?", realLocals: "Echte locals. Echte verhalen. Echte ontdekking.", legal: "Juridisch", securityPayment: "Beveiliging & Betaling", terms: "Servicevoorwaarden", privacy: "Privacybeleid", cancellation: "Annulering & Terugbetaling", distanceSales: "Overeenkomst op afstand", preInfo: "Vooraf-informatieformulier", kvkk: "Kennisgeving gegevensbescherming", cookies: "Cookiebeleid", workingHours: "Openingstijden: Doordeweeks 09:00 – 18:00 (UTC+3)", trustLine: "SSL-beveiligd · Gediplomeerde gidsen · Veilig boeken", trustRatingTitle: "4.9 gemiddeld", trustRatingSub: "Van echte reizigers", trustVerifiedTitle: "100% geverifieerde gidsen", trustVerifiedSub: "ID & licentie gecontroleerd", trustCancelTitle: "Gratis annuleren", trustCancelSub: "Bij de meeste ervaringen", trustInstantTitle: "Direct boeken", trustInstantSub: "In seconden bevestigd" },
  pl: { searchSubtitle: "Odkryj przewodników i wycieczki w pobliżu", searchWhereTo: "Dokąd?", searchTryFood: "Wypróbuj wycieczkę kulinarną…", searchTryPrefix: "Wypróbuj", explore: "Odkrywaj", popular: "Popularne", whatAreYouInto: "Co cię interesuje?", realLocals: "Prawdziwi mieszkańcy. Prawdziwe historie. Prawdziwe odkrycia.", legal: "Informacje prawne", securityPayment: "Bezpieczeństwo i płatności", terms: "Warunki korzystania", privacy: "Polityka prywatności", cancellation: "Anulowanie i zwroty", distanceSales: "Umowa sprzedaży na odległość", preInfo: "Formularz informacji wstępnej", kvkk: "Informacja o ochronie danych", cookies: "Polityka cookies", workingHours: "Godziny pracy: W dni robocze 09:00 – 18:00 (UTC+3)", trustLine: "Ochrona SSL · Licencjonowani przewodnicy · Bezpieczna rezerwacja", trustRatingTitle: "Średnia 4.9", trustRatingSub: "Od prawdziwych podróżnych", trustVerifiedTitle: "100% zweryfikowani przewodnicy", trustVerifiedSub: "Sprawdzony dokument i licencja", trustCancelTitle: "Bezpłatne anulowanie", trustCancelSub: "W większości doświadczeń", trustInstantTitle: "Natychmiastowa rezerwacja", trustInstantSub: "Potwierdzenie w sekundy" },
  uk: { searchSubtitle: "Знайди гідів і тури поруч", searchWhereTo: "Куди?", searchTryFood: "Спробуй гастротур…", searchTryPrefix: "Спробуй", explore: "Переглянути", popular: "Популярне", whatAreYouInto: "Що тобі цікаво?", realLocals: "Справжні місцеві. Справжні історії. Справжні відкриття.", legal: "Правова інформація", securityPayment: "Безпека та оплата", terms: "Умови використання", privacy: "Політика конфіденційності", cancellation: "Скасування та повернення", distanceSales: "Договір дистанційного продажу", preInfo: "Форма попереднього інформування", kvkk: "Повідомлення про захист даних", cookies: "Політика cookie", workingHours: "Години роботи: У будні 09:00 – 18:00 (UTC+3)", trustLine: "SSL-захист · Ліцензовані гіди · Безпечне бронювання", trustRatingTitle: "Рейтинг 4.9", trustRatingSub: "Від справжніх мандрівників", trustVerifiedTitle: "100% перевірені гіди", trustVerifiedSub: "Документи та ліцензія перевірені", trustCancelTitle: "Безкоштовне скасування", trustCancelSub: "На більшості турів", trustInstantTitle: "Миттєве бронювання", trustInstantSub: "Підтвердження за секунди" },
  id: { searchSubtitle: "Temukan pemandu & tur di dekatmu", searchWhereTo: "Mau ke mana?", searchTryFood: "Coba tur kuliner…", searchTryPrefix: "Coba", explore: "Jelajahi", popular: "Populer", whatAreYouInto: "Apa yang kamu suka?", realLocals: "Warga lokal asli. Cerita nyata. Penemuan nyata.", legal: "Legal", securityPayment: "Keamanan & Pembayaran", terms: "Ketentuan Layanan", privacy: "Kebijakan Privasi", cancellation: "Pembatalan & Pengembalian", distanceSales: "Perjanjian Penjualan Jarak Jauh", preInfo: "Formulir Informasi Awal", kvkk: "Pemberitahuan Perlindungan Data", cookies: "Kebijakan Cookie", workingHours: "Jam kerja: Hari kerja 09:00 – 18:00 (UTC+3)", trustLine: "Diamankan SSL · Pemandu berlisensi · Pemesanan aman", trustRatingTitle: "Rating rata-rata 4.9", trustRatingSub: "Dari pelancong asli", trustVerifiedTitle: "Pemandu 100% terverifikasi", trustVerifiedSub: "Identitas & lisensi dicek", trustCancelTitle: "Pembatalan gratis", trustCancelSub: "Di sebagian besar pengalaman", trustInstantTitle: "Pemesanan instan", trustInstantSub: "Konfirmasi dalam detik" },
  pt: { searchSubtitle: "Descobre guias e tours perto de ti", searchWhereTo: "Para onde?", searchTryFood: "Experimenta um tour gastronómico…", searchTryPrefix: "Experimenta", explore: "Explorar", popular: "Populares", whatAreYouInto: "Do que gostas?", realLocals: "Locais a sério. Histórias a sério. Descoberta a sério.", legal: "Legal", securityPayment: "Segurança & Pagamento", terms: "Termos de Serviço", privacy: "Política de Privacidade", cancellation: "Cancelamento & Reembolsos", distanceSales: "Contrato de Venda à Distância", preInfo: "Formulário de Pré-Informação", kvkk: "Aviso de Proteção de Dados", cookies: "Política de Cookies", workingHours: "Horário: Dias úteis 09:00 – 18:00 (UTC+3)", trustLine: "Protegido por SSL · Guias licenciados · Reserva segura", trustRatingTitle: "4,9 de média", trustRatingSub: "De viajantes reais", trustVerifiedTitle: "Guias 100% verificados", trustVerifiedSub: "Documento e licença verificados", trustCancelTitle: "Cancelamento grátis", trustCancelSub: "Na maioria das experiências", trustInstantTitle: "Reserva instantânea", trustInstantSub: "Confirmação em segundos" },
};
