import type { Locale } from "./i18n";

// Ana sayfadaki kalan hardcoded metinler — arama barı, kategori başlığı, trust bar,
// footer legal/çalışma saatleri vb. — 21 dil. Kategori etiketleri için navbar-i18n.
export type UiExtra = {
  searchSubtitle: string;
  searchWhereTo: string;
  searchTryFood: string;
  searchTryPrefix: string; // "Try {city}…" → `${searchTryPrefix} ${city}…`
  explore: string;
  popular: string;
  whatAreYouInto: string;
  realLocals: string;
  legal: string;
  securityPayment: string;
  terms: string;
  privacy: string;
  cancellation: string;
  distanceSales: string;
  preInfo: string;
  kvkk: string;
  cookies: string;
  workingHours: string;
  trustLine: string;
  trustRatingTitle: string;
  trustRatingSub: string;
  trustVerifiedTitle: string;
  trustVerifiedSub: string;
  trustIdTitle: string;
  trustIdSub: string;
  trustPayTitle: string;
  trustPaySub: string;
  trustCancelTitle: string;
  trustCancelSub: string;
  trustInstantTitle: string;
  trustInstantSub: string;
  trustHeading: string;
  trustHeadingSub: string;
};

export const uiExtra: Record<Locale, UiExtra> = {
  en: { searchSubtitle: "Discover guides & tours near you", searchWhereTo: "Where to?", searchTryFood: "Try a food tour…", searchTryPrefix: "Try", explore: "Explore", popular: "Popular", whatAreYouInto: "What are you into?", realLocals: "Real locals. Real stories. Real discovery.", legal: "Legal", securityPayment: "Security & Payment", terms: "Terms of Service", privacy: "Privacy Policy", cancellation: "Cancellation & Refunds", distanceSales: "Distance Sales Agreement", preInfo: "Pre-Information Form", kvkk: "Data Protection Notice", cookies: "Cookie Policy", workingHours: "Working hours: Weekdays 09:00 – 18:00 (UTC+3)", trustLine: "SSL Secured · Licensed Guides · Secure Booking", trustRatingTitle: "4.9 average rating", trustRatingSub: "From real travellers", trustVerifiedTitle: "Licensed local guides", trustVerifiedSub: "Official Ministry of Culture licence", trustIdTitle: "Verified & ID-checked", trustIdSub: "Every guide passes identity checks", trustPayTitle: "Secure in-app payment", trustPaySub: "No cash · transparent pricing", trustCancelTitle: "Money-back protection", trustCancelSub: "Full refund if your tour doesn't happen", trustInstantTitle: "Instant matching", trustInstantSub: "Connect in ~60 seconds", trustHeading: "Why book with VibeGuide?", trustHeadingSub: "Real licensed locals, secure payment, and full money-back protection — every booking.", },
  tr: { searchSubtitle: "Yakınındaki rehber ve turları keşfet", searchWhereTo: "Nereye?", searchTryFood: "Yemek turu dene…", searchTryPrefix: "Dene:", explore: "Keşfet", popular: "Popüler", whatAreYouInto: "Neye ilgin var?", realLocals: "Gerçek yereller. Gerçek hikâyeler. Gerçek keşif.", legal: "Yasal", securityPayment: "Güvenlik & Ödeme", terms: "Kullanım Şartları", privacy: "Gizlilik Politikası", cancellation: "İptal & İade", distanceSales: "Mesafeli Satış Sözleşmesi", preInfo: "Ön Bilgilendirme Formu", kvkk: "KVKK Aydınlatma", cookies: "Çerez Politikası", workingHours: "Çalışma saatleri: Hafta içi 09:00 – 18:00 (UTC+3)", trustLine: "SSL Korumalı · Lisanslı Rehberler · Güvenli Rezervasyon", trustRatingTitle: "4.9 ortalama puan", trustRatingSub: "Gerçek gezginlerden", trustVerifiedTitle: "Lisanslı yerel rehberler", trustVerifiedSub: "Resmi Kültür Bakanlığı lisansı", trustIdTitle: "Doğrulanmış & kimlik kontrollü", trustIdSub: "Her rehber kimlik kontrolünden geçer", trustPayTitle: "Uygulama içi güvenli ödeme", trustPaySub: "Nakit yok · şeffaf fiyat", trustCancelTitle: "Para iadesi güvencesi", trustCancelSub: "Tur gerçekleşmezse tam iade", trustInstantTitle: "Anında eşleşme", trustInstantSub: "~60 saniyede bağlan", trustHeading: "Neden VibeGuide ile rezervasyon yapmalısın?", trustHeadingSub: "Gerçek lisanslı yereller, güvenli ödeme ve tam para iadesi güvencesi — her rezervasyonda.", },
  de: { searchSubtitle: "Entdecke Guides & Touren in deiner Nähe", searchWhereTo: "Wohin?", searchTryFood: "Probier eine Food-Tour…", searchTryPrefix: "Probier", explore: "Entdecken", popular: "Beliebt", whatAreYouInto: "Worauf hast du Lust?", realLocals: "Echte Locals. Echte Geschichten. Echte Entdeckungen.", legal: "Rechtliches", securityPayment: "Sicherheit & Zahlung", terms: "Nutzungsbedingungen", privacy: "Datenschutz", cancellation: "Stornierung & Rückerstattung", distanceSales: "Fernabsatzvertrag", preInfo: "Vorab-Informationsformular", kvkk: "Datenschutzhinweis", cookies: "Cookie-Richtlinie", workingHours: "Öffnungszeiten: Wochentags 09:00 – 18:00 (UTC+3)", trustLine: "SSL-geschützt · Lizenzierte Guides · Sichere Buchung", trustRatingTitle: "4,9 Durchschnitt", trustRatingSub: "Von echten Reisenden", trustVerifiedTitle: "Lizenzierte lokale Guides", trustVerifiedSub: "Offizielle Lizenz des Kulturministeriums", trustIdTitle: "Verifiziert & ID-geprüft", trustIdSub: "Jeder Guide durchläuft eine Identitätsprüfung", trustPayTitle: "Sichere Zahlung in der App", trustPaySub: "Kein Bargeld · transparente Preise", trustCancelTitle: "Geld-zurück-Garantie", trustCancelSub: "Volle Erstattung, wenn deine Tour nicht stattfindet", trustInstantTitle: "Sofortige Vermittlung", trustInstantSub: "Verbindung in ~60 Sekunden", trustHeading: "Warum mit VibeGuide buchen?", trustHeadingSub: "Echte lizenzierte Locals, sichere Zahlung und volle Geld-zurück-Garantie — bei jeder Buchung.", },
  fr: { searchSubtitle: "Découvre guides & visites près de toi", searchWhereTo: "Où aller ?", searchTryFood: "Essaie une visite gourmande…", searchTryPrefix: "Essaie", explore: "Explorer", popular: "Populaire", whatAreYouInto: "Qu'est-ce qui te tente ?", realLocals: "De vrais locaux. De vraies histoires. De vraies découvertes.", legal: "Mentions légales", securityPayment: "Sécurité & Paiement", terms: "Conditions d'utilisation", privacy: "Politique de confidentialité", cancellation: "Annulation & Remboursement", distanceSales: "Contrat de vente à distance", preInfo: "Formulaire de pré-information", kvkk: "Avis de protection des données", cookies: "Politique de cookies", workingHours: "Heures d'ouverture : En semaine 09:00 – 18:00 (UTC+3)", trustLine: "SSL sécurisé · Guides agréés · Réservation sécurisée", trustRatingTitle: "4,9 de moyenne", trustRatingSub: "De vrais voyageurs", trustVerifiedTitle: "Guides locaux agréés", trustVerifiedSub: "Licence officielle du ministère de la Culture", trustIdTitle: "Vérifiés & identité contrôlée", trustIdSub: "Chaque guide passe un contrôle d'identité", trustPayTitle: "Paiement sécurisé dans l'app", trustPaySub: "Sans espèces · tarifs transparents", trustCancelTitle: "Garantie remboursement", trustCancelSub: "Remboursement intégral si votre visite n'a pas lieu", trustInstantTitle: "Mise en relation instantanée", trustInstantSub: "Connexion en ~60 secondes", trustHeading: "Pourquoi réserver avec VibeGuide ?", trustHeadingSub: "De vrais locaux agréés, un paiement sécurisé et une garantie de remboursement — à chaque réservation.", },
  hr: { searchSubtitle: "Otkrij vodiče i ture u blizini", searchWhereTo: "Kamo?", searchTryFood: "Probaj gastro turu…", searchTryPrefix: "Probaj", explore: "Istraži", popular: "Popularno", whatAreYouInto: "Što te zanima?", realLocals: "Pravi mještani. Prave priče. Pravo otkriće.", legal: "Pravno", securityPayment: "Sigurnost i plaćanje", terms: "Uvjeti korištenja", privacy: "Pravila privatnosti", cancellation: "Otkazivanje i povrat", distanceSales: "Ugovor o prodaji na daljinu", preInfo: "Obrazac prethodne obavijesti", kvkk: "Obavijest o zaštiti podataka", cookies: "Pravila o kolačićima", workingHours: "Radno vrijeme: Radnim danom 09:00 – 18:00 (UTC+3)", trustLine: "SSL zaštita · Licencirani vodiči · Sigurna rezervacija", trustRatingTitle: "Prosječna ocjena 4.9", trustRatingSub: "Od pravih putnika", trustVerifiedTitle: "Licencirani lokalni vodiči", trustVerifiedSub: "Službena licenca Ministarstva kulture", trustIdTitle: "Provjereni i s provjerom identiteta", trustIdSub: "Svaki vodič prolazi provjeru identiteta", trustPayTitle: "Sigurno plaćanje u aplikaciji", trustPaySub: "Bez gotovine · transparentne cijene", trustCancelTitle: "Zaštita povrata novca", trustCancelSub: "Potpuni povrat ako se vaš obilazak ne održi", trustInstantTitle: "Trenutno povezivanje", trustInstantSub: "Povezivanje za ~60 sekundi", trustHeading: "Zašto rezervirati uz VibeGuide?", trustHeadingSub: "Pravi licencirani mještani, sigurno plaćanje i potpuna zaštita povrata novca — za svaku rezervaciju.", },
  ro: { searchSubtitle: "Descoperă ghizi și tururi din apropiere", searchWhereTo: "Încotro?", searchTryFood: "Încearcă un tur culinar…", searchTryPrefix: "Încearcă", explore: "Explorează", popular: "Populare", whatAreYouInto: "Ce te pasionează?", realLocals: "Localnici reali. Povești reale. Descoperire reală.", legal: "Legal", securityPayment: "Securitate & Plată", terms: "Termeni și condiții", privacy: "Politica de confidențialitate", cancellation: "Anulare & Rambursare", distanceSales: "Contract de vânzare la distanță", preInfo: "Formular de pre-informare", kvkk: "Notă privind protecția datelor", cookies: "Politica de cookie-uri", workingHours: "Program: În timpul săptămânii 09:00 – 18:00 (UTC+3)", trustLine: "Protejat SSL · Ghizi licențiați · Rezervare sigură", trustRatingTitle: "Rating mediu 4.9", trustRatingSub: "De la călători reali", trustVerifiedTitle: "Ghizi locali licențiați", trustVerifiedSub: "Licență oficială a Ministerului Culturii", trustIdTitle: "Verificați și cu identitate confirmată", trustIdSub: "Fiecare ghid trece verificarea identității", trustPayTitle: "Plată securizată în aplicație", trustPaySub: "Fără numerar · prețuri transparente", trustCancelTitle: "Protecție cu returnarea banilor", trustCancelSub: "Rambursare integrală dacă turul nu are loc", trustInstantTitle: "Potrivire instantanee", trustInstantSub: "Conectare în ~60 de secunde", trustHeading: "De ce să rezervi cu VibeGuide?", trustHeadingSub: "Localnici licențiați reali, plată sigură și garanție completă de rambursare — la fiecare rezervare.", },
  zh: { searchSubtitle: "发现你附近的向导和行程", searchWhereTo: "去哪里？", searchTryFood: "试试美食之旅…", searchTryPrefix: "试试", explore: "探索", popular: "热门", whatAreYouInto: "你喜欢什么？", realLocals: "真实的当地人。真实的故事。真实的发现。", legal: "法律", securityPayment: "安全与支付", terms: "服务条款", privacy: "隐私政策", cancellation: "取消与退款", distanceSales: "远程销售协议", preInfo: "预先告知表", kvkk: "数据保护声明", cookies: "Cookie 政策", workingHours: "工作时间：工作日 09:00 – 18:00 (UTC+3)", trustLine: "SSL 加密 · 持证向导 · 安全预订", trustRatingTitle: "4.9 平均评分", trustRatingSub: "来自真实旅行者", trustVerifiedTitle: "持牌本地向导", trustVerifiedSub: "文化部官方执照", trustIdTitle: "已验证并核验身份", trustIdSub: "每位向导均通过身份核验", trustPayTitle: "应用内安全支付", trustPaySub: "无需现金 · 价格透明", trustCancelTitle: "退款保障", trustCancelSub: "若行程未成行可全额退款", trustInstantTitle: "即时匹配", trustInstantSub: "约60秒内连接", trustHeading: "为什么选择 VibeGuide 预订？", trustHeadingSub: "真正持证的当地人、安全支付和全额退款保障——每一次预订。", },
  ru: { searchSubtitle: "Найди гидов и туры рядом", searchWhereTo: "Куда?", searchTryFood: "Попробуй гастротур…", searchTryPrefix: "Попробуй", explore: "Смотреть", popular: "Популярное", whatAreYouInto: "Что тебе интересно?", realLocals: "Настоящие местные. Настоящие истории. Настоящие открытия.", legal: "Правовая информация", securityPayment: "Безопасность и оплата", terms: "Условия использования", privacy: "Политика конфиденциальности", cancellation: "Отмена и возврат", distanceSales: "Договор дистанционной продажи", preInfo: "Форма предварительного уведомления", kvkk: "Уведомление о защите данных", cookies: "Политика cookie", workingHours: "Часы работы: По будням 09:00 – 18:00 (UTC+3)", trustLine: "SSL-защита · Лицензированные гиды · Безопасное бронирование", trustRatingTitle: "Рейтинг 4.9", trustRatingSub: "От настоящих путешественников", trustVerifiedTitle: "Лицензированные местные гиды", trustVerifiedSub: "Официальная лицензия Министерства культуры", trustIdTitle: "Проверены, личность подтверждена", trustIdSub: "Каждый гид проходит проверку личности", trustPayTitle: "Безопасная оплата в приложении", trustPaySub: "Без наличных · прозрачные цены", trustCancelTitle: "Гарантия возврата средств", trustCancelSub: "Полный возврат, если тур не состоится", trustInstantTitle: "Мгновенный подбор", trustInstantSub: "Связь за ~60 секунд", trustHeading: "Почему стоит бронировать с VibeGuide?", trustHeadingSub: "Настоящие лицензированные местные, безопасная оплата и полная гарантия возврата — в каждом бронировании.", },
  es: { searchSubtitle: "Descubre guías y tours cerca de ti", searchWhereTo: "¿A dónde?", searchTryFood: "Prueba un tour gastronómico…", searchTryPrefix: "Prueba", explore: "Explorar", popular: "Popular", whatAreYouInto: "¿Qué te gusta?", realLocals: "Locales de verdad. Historias de verdad. Descubrimiento de verdad.", legal: "Legal", securityPayment: "Seguridad y Pago", terms: "Términos de servicio", privacy: "Política de privacidad", cancellation: "Cancelación y Reembolsos", distanceSales: "Contrato de venta a distancia", preInfo: "Formulario de información previa", kvkk: "Aviso de protección de datos", cookies: "Política de cookies", workingHours: "Horario: Días laborables 09:00 – 18:00 (UTC+3)", trustLine: "Protegido con SSL · Guías con licencia · Reserva segura", trustRatingTitle: "4,9 de media", trustRatingSub: "De viajeros reales", trustVerifiedTitle: "Guías locales con licencia", trustVerifiedSub: "Licencia oficial del Ministerio de Cultura", trustIdTitle: "Verificados y con identidad comprobada", trustIdSub: "Cada guía pasa controles de identidad", trustPayTitle: "Pago seguro en la app", trustPaySub: "Sin efectivo · precios transparentes", trustCancelTitle: "Garantía de reembolso", trustCancelSub: "Reembolso total si tu tour no se realiza", trustInstantTitle: "Conexión instantánea", trustInstantSub: "Conecta en ~60 segundos", trustHeading: "¿Por qué reservar con VibeGuide?", trustHeadingSub: "Locales con licencia reales, pago seguro y garantía total de reembolso — en cada reserva.", },
  ko: { searchSubtitle: "주변의 가이드와 투어를 둘러보세요", searchWhereTo: "어디로?", searchTryFood: "푸드 투어 어때요…", searchTryPrefix: "추천:", explore: "탐색", popular: "인기", whatAreYouInto: "무엇에 관심 있나요?", realLocals: "진짜 현지인. 진짜 이야기. 진짜 발견.", legal: "법적 고지", securityPayment: "보안 & 결제", terms: "이용약관", privacy: "개인정보 처리방침", cancellation: "취소 & 환불", distanceSales: "통신판매 계약", preInfo: "사전 정보 양식", kvkk: "개인정보 보호 고지", cookies: "쿠키 정책", workingHours: "운영 시간: 평일 09:00 – 18:00 (UTC+3)", trustLine: "SSL 보안 · 공인 가이드 · 안전한 예약", trustRatingTitle: "평균 4.9점", trustRatingSub: "실제 여행자 평가", trustVerifiedTitle: "면허 보유 현지 가이드", trustVerifiedSub: "문화부 공식 라이선스", trustIdTitle: "검증 및 신원 확인 완료", trustIdSub: "모든 가이드가 신원 확인을 거칩니다", trustPayTitle: "앱 내 안전 결제", trustPaySub: "현금 불필요 · 투명한 가격", trustCancelTitle: "환불 보장", trustCancelSub: "투어가 진행되지 않으면 전액 환불", trustInstantTitle: "즉시 매칭", trustInstantSub: "약 60초 만에 연결", trustHeading: "왜 VibeGuide로 예약해야 할까요?", trustHeadingSub: "진짜 면허 보유 현지인, 안전한 결제, 전액 환불 보장 — 모든 예약에.", },
  el: { searchSubtitle: "Ανακάλυψε ξεναγούς & ξεναγήσεις κοντά σου", searchWhereTo: "Πού πας;", searchTryFood: "Δοκίμασε γαστρονομική ξενάγηση…", searchTryPrefix: "Δοκίμασε", explore: "Εξερεύνηση", popular: "Δημοφιλή", whatAreYouInto: "Τι σου αρέσει;", realLocals: "Αληθινοί ντόπιοι. Αληθινές ιστορίες. Αληθινή ανακάλυψη.", legal: "Νομικά", securityPayment: "Ασφάλεια & Πληρωμή", terms: "Όροι χρήσης", privacy: "Πολιτική απορρήτου", cancellation: "Ακύρωση & Επιστροφές", distanceSales: "Σύμβαση εξ αποστάσεως πώλησης", preInfo: "Έντυπο προ-ενημέρωσης", kvkk: "Ειδοποίηση προστασίας δεδομένων", cookies: "Πολιτική cookies", workingHours: "Ώρες λειτουργίας: Καθημερινές 09:00 – 18:00 (UTC+3)", trustLine: "Προστασία SSL · Αδειούχοι ξεναγοί · Ασφαλής κράτηση", trustRatingTitle: "4.9 μέση βαθμολογία", trustRatingSub: "Από αληθινούς ταξιδιώτες", trustVerifiedTitle: "Αδειοδοτημένοι τοπικοί ξεναγοί", trustVerifiedSub: "Επίσημη άδεια του Υπουργείου Πολιτισμού", trustIdTitle: "Επαληθευμένοι & με έλεγχο ταυτότητας", trustIdSub: "Κάθε ξεναγός περνά έλεγχο ταυτότητας", trustPayTitle: "Ασφαλής πληρωμή εντός εφαρμογής", trustPaySub: "Χωρίς μετρητά · διαφανείς τιμές", trustCancelTitle: "Προστασία επιστροφής χρημάτων", trustCancelSub: "Πλήρης επιστροφή αν δεν πραγματοποιηθεί η ξενάγηση", trustInstantTitle: "Άμεση αντιστοίχιση", trustInstantSub: "Σύνδεση σε ~60 δευτερόλεπτα", trustHeading: "Γιατί να κλείσεις με το VibeGuide;", trustHeadingSub: "Πραγματικοί αδειούχοι ντόπιοι, ασφαλής πληρωμή και πλήρης εγγύηση επιστροφής χρημάτων — σε κάθε κράτηση.", },
  ja: { searchSubtitle: "近くのガイドとツアーを見つけよう", searchWhereTo: "どこへ？", searchTryFood: "フードツアーはいかが…", searchTryPrefix: "おすすめ:", explore: "探す", popular: "人気", whatAreYouInto: "何に興味がある？", realLocals: "本物の地元の人。本物の物語。本物の発見。", legal: "法的情報", securityPayment: "セキュリティと支払い", terms: "利用規約", privacy: "プライバシーポリシー", cancellation: "キャンセルと返金", distanceSales: "通信販売契約", preInfo: "事前情報フォーム", kvkk: "データ保護に関する通知", cookies: "Cookie ポリシー", workingHours: "営業時間: 平日 09:00 – 18:00 (UTC+3)", trustLine: "SSL保護 · 公認ガイド · 安全な予約", trustRatingTitle: "平均4.9", trustRatingSub: "本物の旅行者から", trustVerifiedTitle: "公認の現地ガイド", trustVerifiedSub: "文化省公認ライセンス", trustIdTitle: "本人確認済み", trustIdSub: "すべてのガイドが本人確認を通過", trustPayTitle: "アプリ内安全決済", trustPaySub: "現金不要 · 透明な料金", trustCancelTitle: "返金保証", trustCancelSub: "ツアーが実施されない場合は全額返金", trustInstantTitle: "即時マッチング", trustInstantSub: "約60秒で接続", trustHeading: "VibeGuideで予約する理由", trustHeadingSub: "本物の公認ローカル、安全な決済、全額返金保証——すべての予約に。", },
  bg: { searchSubtitle: "Открий водачи и турове наблизо", searchWhereTo: "Накъде?", searchTryFood: "Опитай кулинарен тур…", searchTryPrefix: "Опитай", explore: "Разгледай", popular: "Популярни", whatAreYouInto: "Какво те влече?", realLocals: "Истински местни. Истински истории. Истинско откритие.", legal: "Правна информация", securityPayment: "Сигурност и плащане", terms: "Условия за ползване", privacy: "Политика за поверителност", cancellation: "Анулиране и възстановяване", distanceSales: "Договор за продажба от разстояние", preInfo: "Формуляр за предварителна информация", kvkk: "Известие за защита на данните", cookies: "Политика за бисквитки", workingHours: "Работно време: Делнични дни 09:00 – 18:00 (UTC+3)", trustLine: "SSL защита · Лицензирани водачи · Сигурна резервация", trustRatingTitle: "Рейтинг 4.9", trustRatingSub: "От истински пътешественици", trustVerifiedTitle: "Лицензирани местни водачи", trustVerifiedSub: "Официален лиценз на Министерството на културата", trustIdTitle: "Проверени и с потвърдена самоличност", trustIdSub: "Всеки водач преминава проверка на самоличността", trustPayTitle: "Сигурно плащане в приложението", trustPaySub: "Без пари в брой · прозрачни цени", trustCancelTitle: "Гаранция за връщане на парите", trustCancelSub: "Пълно възстановяване, ако турът не се състои", trustInstantTitle: "Мигновено свързване", trustInstantSub: "Връзка за ~60 секунди", trustHeading: "Защо да резервираш с VibeGuide?", trustHeadingSub: "Истински лицензирани местни, сигурно плащане и пълна гаранция за връщане на парите — при всяка резервация.", },
  sr: { searchSubtitle: "Otkrij vodiče i ture u blizini", searchWhereTo: "Kuda?", searchTryFood: "Probaj gastro turu…", searchTryPrefix: "Probaj", explore: "Istraži", popular: "Popularno", whatAreYouInto: "Šta te zanima?", realLocals: "Pravi meštani. Prave priče. Pravo otkriće.", legal: "Pravno", securityPayment: "Bezbednost i plaćanje", terms: "Uslovi korišćenja", privacy: "Politika privatnosti", cancellation: "Otkazivanje i povraćaj", distanceSales: "Ugovor o prodaji na daljinu", preInfo: "Obrazac prethodnog obaveštenja", kvkk: "Obaveštenje o zaštiti podataka", cookies: "Politika kolačića", workingHours: "Radno vreme: Radnim danima 09:00 – 18:00 (UTC+3)", trustLine: "SSL zaštita · Licencirani vodiči · Bezbedna rezervacija", trustRatingTitle: "Prosečna ocena 4.9", trustRatingSub: "Od pravih putnika", trustVerifiedTitle: "Licencirani lokalni vodiči", trustVerifiedSub: "Zvanična licenca Ministarstva kulture", trustIdTitle: "Provereni i sa potvrđenim identitetom", trustIdSub: "Svaki vodič prolazi proveru identiteta", trustPayTitle: "Bezbedno plaćanje u aplikaciji", trustPaySub: "Bez gotovine · transparentne cene", trustCancelTitle: "Garancija povraćaja novca", trustCancelSub: "Pun povraćaj ako se tura ne održi", trustInstantTitle: "Trenutno povezivanje", trustInstantSub: "Povezivanje za ~60 sekundi", trustHeading: "Zašto rezervisati uz VibeGuide?", trustHeadingSub: "Pravi licencirani meštani, bezbedno plaćanje i potpuna garancija povraćaja novca — za svaku rezervaciju.", },
  it: { searchSubtitle: "Scopri guide e tour vicino a te", searchWhereTo: "Dove?", searchTryFood: "Prova un tour gastronomico…", searchTryPrefix: "Prova", explore: "Esplora", popular: "Popolari", whatAreYouInto: "Cosa ti piace?", realLocals: "Veri local. Vere storie. Vera scoperta.", legal: "Note legali", securityPayment: "Sicurezza e Pagamento", terms: "Termini di servizio", privacy: "Informativa sulla privacy", cancellation: "Cancellazione e Rimborsi", distanceSales: "Contratto di vendita a distanza", preInfo: "Modulo di pre-informazione", kvkk: "Informativa sulla protezione dei dati", cookies: "Politica sui cookie", workingHours: "Orari: Giorni feriali 09:00 – 18:00 (UTC+3)", trustLine: "Protetto da SSL · Guide autorizzate · Prenotazione sicura", trustRatingTitle: "4,9 di media", trustRatingSub: "Da veri viaggiatori", trustVerifiedTitle: "Guide locali con licenza", trustVerifiedSub: "Licenza ufficiale del Ministero della Cultura", trustIdTitle: "Verificate e con identità controllata", trustIdSub: "Ogni guida supera i controlli di identità", trustPayTitle: "Pagamento sicuro nell'app", trustPaySub: "Niente contanti · prezzi trasparenti", trustCancelTitle: "Garanzia di rimborso", trustCancelSub: "Rimborso totale se il tuo tour non si svolge", trustInstantTitle: "Abbinamento istantaneo", trustInstantSub: "Connessione in ~60 secondi", trustHeading: "Perché prenotare con VibeGuide?", trustHeadingSub: "Veri local autorizzati, pagamento sicuro e garanzia di rimborso totale — in ogni prenotazione.", },
  ar: { searchSubtitle: "اكتشف المرشدين والجولات القريبة منك", searchWhereTo: "إلى أين؟", searchTryFood: "جرّب جولة طعام…", searchTryPrefix: "جرّب", explore: "استكشف", popular: "الأكثر رواجًا", whatAreYouInto: "ما الذي يثير اهتمامك؟", realLocals: "سكان حقيقيون. قصص حقيقية. اكتشاف حقيقي.", legal: "قانوني", securityPayment: "الأمان والدفع", terms: "شروط الخدمة", privacy: "سياسة الخصوصية", cancellation: "الإلغاء والاسترداد", distanceSales: "عقد البيع عن بُعد", preInfo: "نموذج المعلومات المسبقة", kvkk: "إشعار حماية البيانات", cookies: "سياسة ملفات تعريف الارتباط", workingHours: "ساعات العمل: أيام الأسبوع 09:00 – 18:00 (UTC+3)", trustLine: "محمي بـ SSL · مرشدون مرخّصون · حجز آمن", trustRatingTitle: "متوسط التقييم 4.9", trustRatingSub: "من مسافرين حقيقيين", trustVerifiedTitle: "مرشدون محليون مرخّصون", trustVerifiedSub: "ترخيص رسمي من وزارة الثقافة", trustIdTitle: "موثّقون ومدقّقو الهوية", trustIdSub: "كل مرشد يجتاز التحقق من الهوية", trustPayTitle: "دفع آمن داخل التطبيق", trustPaySub: "بدون نقد · تسعير شفاف", trustCancelTitle: "ضمان استرداد الأموال", trustCancelSub: "استرداد كامل إذا لم تتم جولتك", trustInstantTitle: "مطابقة فورية", trustInstantSub: "تواصل خلال ~60 ثانية", trustHeading: "لماذا تحجز مع VibeGuide؟", trustHeadingSub: "سكان محليون مرخّصون حقيقيون، ودفع آمن، وضمان استرداد كامل للأموال — مع كل حجز.", },
  nl: { searchSubtitle: "Ontdek gidsen & tours bij jou in de buurt", searchWhereTo: "Waarheen?", searchTryFood: "Probeer een foodtour…", searchTryPrefix: "Probeer", explore: "Ontdekken", popular: "Populair", whatAreYouInto: "Waar hou je van?", realLocals: "Echte locals. Echte verhalen. Echte ontdekking.", legal: "Juridisch", securityPayment: "Beveiliging & Betaling", terms: "Servicevoorwaarden", privacy: "Privacybeleid", cancellation: "Annulering & Terugbetaling", distanceSales: "Overeenkomst op afstand", preInfo: "Vooraf-informatieformulier", kvkk: "Kennisgeving gegevensbescherming", cookies: "Cookiebeleid", workingHours: "Openingstijden: Doordeweeks 09:00 – 18:00 (UTC+3)", trustLine: "SSL-beveiligd · Gediplomeerde gidsen · Veilig boeken", trustRatingTitle: "4.9 gemiddeld", trustRatingSub: "Van echte reizigers", trustVerifiedTitle: "Erkende lokale gidsen", trustVerifiedSub: "Officiële licentie van het Ministerie van Cultuur", trustIdTitle: "Geverifieerd & ID-gecontroleerd", trustIdSub: "Elke gids doorloopt een identiteitscontrole", trustPayTitle: "Veilig betalen in de app", trustPaySub: "Geen contant geld · transparante prijzen", trustCancelTitle: "Geld-terug-garantie", trustCancelSub: "Volledige terugbetaling als je tour niet doorgaat", trustInstantTitle: "Directe matching", trustInstantSub: "Verbonden in ~60 seconden", trustHeading: "Waarom boeken met VibeGuide?", trustHeadingSub: "Echte gediplomeerde locals, veilige betaling en volledige geld-terug-garantie — bij elke boeking.", },
  pl: { searchSubtitle: "Odkryj przewodników i wycieczki w pobliżu", searchWhereTo: "Dokąd?", searchTryFood: "Wypróbuj wycieczkę kulinarną…", searchTryPrefix: "Wypróbuj", explore: "Odkrywaj", popular: "Popularne", whatAreYouInto: "Co cię interesuje?", realLocals: "Prawdziwi mieszkańcy. Prawdziwe historie. Prawdziwe odkrycia.", legal: "Informacje prawne", securityPayment: "Bezpieczeństwo i płatności", terms: "Warunki korzystania", privacy: "Polityka prywatności", cancellation: "Anulowanie i zwroty", distanceSales: "Umowa sprzedaży na odległość", preInfo: "Formularz informacji wstępnej", kvkk: "Informacja o ochronie danych", cookies: "Polityka cookies", workingHours: "Godziny pracy: W dni robocze 09:00 – 18:00 (UTC+3)", trustLine: "Ochrona SSL · Licencjonowani przewodnicy · Bezpieczna rezerwacja", trustRatingTitle: "Średnia 4.9", trustRatingSub: "Od prawdziwych podróżnych", trustVerifiedTitle: "Licencjonowani lokalni przewodnicy", trustVerifiedSub: "Oficjalna licencja Ministerstwa Kultury", trustIdTitle: "Zweryfikowani i sprawdzeni tożsamościowo", trustIdSub: "Każdy przewodnik przechodzi weryfikację tożsamości", trustPayTitle: "Bezpieczna płatność w aplikacji", trustPaySub: "Bez gotówki · przejrzyste ceny", trustCancelTitle: "Gwarancja zwrotu pieniędzy", trustCancelSub: "Pełny zwrot, jeśli Twoja wycieczka się nie odbędzie", trustInstantTitle: "Natychmiastowe dopasowanie", trustInstantSub: "Połączenie w ~60 sekund", trustHeading: "Dlaczego rezerwować z VibeGuide?", trustHeadingSub: "Prawdziwi licencjonowani mieszkańcy, bezpieczna płatność i pełna gwarancja zwrotu pieniędzy — przy każdej rezerwacji.", },
  uk: { searchSubtitle: "Знайди гідів і тури поруч", searchWhereTo: "Куди?", searchTryFood: "Спробуй гастротур…", searchTryPrefix: "Спробуй", explore: "Переглянути", popular: "Популярне", whatAreYouInto: "Що тобі цікаво?", realLocals: "Справжні місцеві. Справжні історії. Справжні відкриття.", legal: "Правова інформація", securityPayment: "Безпека та оплата", terms: "Умови використання", privacy: "Політика конфіденційності", cancellation: "Скасування та повернення", distanceSales: "Договір дистанційного продажу", preInfo: "Форма попереднього інформування", kvkk: "Повідомлення про захист даних", cookies: "Політика cookie", workingHours: "Години роботи: У будні 09:00 – 18:00 (UTC+3)", trustLine: "SSL-захист · Ліцензовані гіди · Безпечне бронювання", trustRatingTitle: "Рейтинг 4.9", trustRatingSub: "Від справжніх мандрівників", trustVerifiedTitle: "Ліцензовані місцеві гіди", trustVerifiedSub: "Офіційна ліцензія Міністерства культури", trustIdTitle: "Перевірені, особу підтверджено", trustIdSub: "Кожен гід проходить перевірку особи", trustPayTitle: "Безпечна оплата в застосунку", trustPaySub: "Без готівки · прозорі ціни", trustCancelTitle: "Гарантія повернення коштів", trustCancelSub: "Повне повернення, якщо тур не відбудеться", trustInstantTitle: "Миттєвий підбір", trustInstantSub: "Зв’язок за ~60 секунд", trustHeading: "Чому варто бронювати з VibeGuide?", trustHeadingSub: "Справжні ліцензовані місцеві, безпечна оплата та повна гарантія повернення коштів — у кожному бронюванні.", },
  id: { searchSubtitle: "Temukan pemandu & tur di dekatmu", searchWhereTo: "Mau ke mana?", searchTryFood: "Coba tur kuliner…", searchTryPrefix: "Coba", explore: "Jelajahi", popular: "Populer", whatAreYouInto: "Apa yang kamu suka?", realLocals: "Warga lokal asli. Cerita nyata. Penemuan nyata.", legal: "Legal", securityPayment: "Keamanan & Pembayaran", terms: "Ketentuan Layanan", privacy: "Kebijakan Privasi", cancellation: "Pembatalan & Pengembalian", distanceSales: "Perjanjian Penjualan Jarak Jauh", preInfo: "Formulir Informasi Awal", kvkk: "Pemberitahuan Perlindungan Data", cookies: "Kebijakan Cookie", workingHours: "Jam kerja: Hari kerja 09:00 – 18:00 (UTC+3)", trustLine: "Diamankan SSL · Pemandu berlisensi · Pemesanan aman", trustRatingTitle: "Rating rata-rata 4.9", trustRatingSub: "Dari pelancong asli", trustVerifiedTitle: "Pemandu lokal berlisensi", trustVerifiedSub: "Lisensi resmi Kementerian Kebudayaan", trustIdTitle: "Terverifikasi & identitas dicek", trustIdSub: "Setiap pemandu lolos pemeriksaan identitas", trustPayTitle: "Pembayaran aman dalam aplikasi", trustPaySub: "Tanpa tunai · harga transparan", trustCancelTitle: "Jaminan uang kembali", trustCancelSub: "Pengembalian penuh jika tur Anda tidak berlangsung", trustInstantTitle: "Pencocokan instan", trustInstantSub: "Terhubung dalam ~60 detik", trustHeading: "Mengapa pesan dengan VibeGuide?", trustHeadingSub: "Warga lokal berlisensi asli, pembayaran aman, dan jaminan uang kembali penuh — di setiap pemesanan.", },
  pt: { searchSubtitle: "Descobre guias e tours perto de ti", searchWhereTo: "Para onde?", searchTryFood: "Experimenta um tour gastronómico…", searchTryPrefix: "Experimenta", explore: "Explorar", popular: "Populares", whatAreYouInto: "Do que gostas?", realLocals: "Locais a sério. Histórias a sério. Descoberta a sério.", legal: "Legal", securityPayment: "Segurança & Pagamento", terms: "Termos de Serviço", privacy: "Política de Privacidade", cancellation: "Cancelamento & Reembolsos", distanceSales: "Contrato de Venda à Distância", preInfo: "Formulário de Pré-Informação", kvkk: "Aviso de Proteção de Dados", cookies: "Política de Cookies", workingHours: "Horário: Dias úteis 09:00 – 18:00 (UTC+3)", trustLine: "Protegido por SSL · Guias licenciados · Reserva segura", trustRatingTitle: "4,9 de média", trustRatingSub: "De viajantes reais", trustVerifiedTitle: "Guias locais licenciados", trustVerifiedSub: "Licença oficial do Ministério da Cultura", trustIdTitle: "Verificados e com identidade confirmada", trustIdSub: "Cada guia passa por verificação de identidade", trustPayTitle: "Pagamento seguro no app", trustPaySub: "Sem dinheiro · preços transparentes", trustCancelTitle: "Garantia de reembolso", trustCancelSub: "Reembolso total se o seu tour não acontecer", trustInstantTitle: "Conexão instantânea", trustInstantSub: "Conecte em ~60 segundos", trustHeading: "Porquê reservar com a VibeGuide?", trustHeadingSub: "Locais licenciados reais, pagamento seguro e garantia total de reembolso — em cada reserva.", },
};
